### PR TITLE
Update the VP of IA name

### LINKED ISSUE #524: Update Membership Page Text
Update the VP of IA name -> `Christian Ayala`

image

### PR DESCRIPTION
**Pull request by Peri7at**
Fixes #524 

## Description

This PR updates membership page text.

Before:

image

After:

Screen Shot 2022-09-01 at 23 38 03

### CODE REVIEW

**Comment by LeftAutomated** [comment]
@Peri7at Thanks for taking this on! 
The build is failing right now. Eslint is a tool we use to standardize code formatting.
Could you run `yarn eslint-fix` on your changes and commit the new changes?

**Comment by Peri7at** [comment]
> yarn eslint-fix

@LeftAutomated Thank you for reviewing. I could run the project just after running `yarn eslint-fix`, with single quotes Eslint gave an error, so I made my changes and opened PR after already running Eslint tool. I tried again but this is the result (double quotes) after running `yarn eslint-fix`:

image

**Comment by Peri7at** [comment]
> @Peri7at Thanks for taking this on!
> The build is failing right now. Eslint is a tool we use to standardize code formatting.
> Could you run `yarn eslint-fix` on your changes and commit the new changes?

**Comment by Peri7at** [comment]
> @Peri7at Thanks for taking this on!
> The build is failing right now. Eslint is a tool we use to standardize code formatting.
> Could you run `yarn eslint-fix` on your changes and commit the new changes?

@LeftAutomated Shall I manually change double quotes to single quotes and push again?

**Comment by LeftAutomated** [comment]
> > @Peri7at Thanks for taking this on!
> > The build is failing right now. Eslint is a tool we use to standardize code formatting.
> > Could you run `yarn eslint-fix` on your changes and commit the new changes?
> 
> @LeftAutomated Shall I manually change double quotes to single quotes and push again?

@Peri7at The quotes and tabs are different from our lint configuration. If you have any formatting extensions on VS Code, try disabling those and revert your changes. Afterward, make the VP of IA name change.

**Comment by Peri7at** [comment]
> > > @Peri7at Thanks for taking this on!
> > > The build is failing right now. Eslint is a tool we use to standardize code formatting.
> > > Could you run `yarn eslint-fix` on your changes and commit the new changes?
> > 
> > 
> > @LeftAutomated Shall I manually change double quotes to single quotes and push again?
> 
> @Peri7at The quotes and tabs are different from our lint configuration. If you have any formatting extensions on VS Code, try disabling those and revert your changes. Afterward, make the VP of IA name change.

@LeftAutomated Could please review the last commit?

**Review by LeftAutomated — APPROVED** [review]

**Pull request merged**
