### PR TITLE
Updates to tutoring page

### PR DESCRIPTION
**Pull request by shubhsheth**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [X] 🚩 Other

## Description
Updated Text on the Tutoring Page

Closing Tutoring Page Revamp

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Review by vyas0189 — APPROVED** [review]

**Comment by shubhsheth** [comment]
Don't merge yet working on fixing package versions

**Review by KevFlo — APPROVED** [review]

**Comment by crudemandarin** [comment]
@vyas0189 @shubhsheth @KevFlo Hey team! I see this PR was merged. When will we see these changes reflected in the deployment? Thank you!

**Comment by vyas0189** [comment]
> @vyas0189 @shubhsheth @KevFlo Hey team! I see this PR was merged. When will we see these changes reflected in the deployment? Thank you!

Make a PR from master to prod

**Comment by crudemandarin** [comment]
> > @vyas0189 @shubhsheth @KevFlo Hey team! I see this PR was merged. When will we see these changes reflected in the deployment? Thank you!
> 
> Make a PR from master to prod

@shubhsheth could you make this PR?

**Comment by shubhsheth** [comment]
@crudemandarin Kevin already pushed it #232

**Comment by vyas0189** [comment]
> @vyas0189 @shubhsheth @KevFlo Hey team! I see this PR was merged. When will we see these changes reflected in the deployment? Thank you!

The changes will take effect immediately after the CD is done

**Pull request merged**
