### PR TITLE
Officer update

### PR DESCRIPTION
**Pull request by KevFlo**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [x] 🔖 Release
- [ ] 🚩 Other

## Description
#396 

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Mobile & Desktop Screenshots/Recordings
Screen Shot 2022-01-22 at 12 10 31 AM

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by vyas0189** [comment]
Please reduce the size of the image, image has to be less than 100KB.

**Review by vyas0189 — CHANGES_REQUESTED** [review]
Please reduce the size of the images, each image has to be less than 100KB

**Comment by KevFlo** [comment]
> Please reduce the size of the images, each image has to be less than 100KB

Done still getting some issue, is it still the size that is the problem?

**Comment by KevFlo** [comment]
Thank god 
@vyas0189 it worked!

**Review by vyas0189 — APPROVED** [review]

**Pull request merged**
