### PR TITLE
updating officers and boot strap version

### PR DESCRIPTION
**Pull request by KevFlo**

### CODE REVIEW

**Comment by vyas0189** [comment]
There is a problem with the position of the officer picture. I circled the ones with the problem
Screenshot_20210604-084440

**Comment by KevFlo** [comment]
i see that, must be issue with the jpg sizes, ill work on it after I  get back from airport

**Comment by KevFlo** [comment]
i see it in vercel still getting cropped, will work on cropping instead of rescaling

**Comment by shubhsheth** [comment]
@KevFlo If you can, try to get it close to the linkedin post of the officers

**Comment by shubhsheth** [comment]
@KevFlo You're missing some officers (DO CodeRED, DO Operations atleast)

**Comment by KevFlo** [comment]
> @KevFlo You're missing some officers (DO CodeRED, DO Operations atleast)

I was wondering why they weren't on the website before I started working on it, will add right now

**Comment by vyas0189** [comment]
@shubhsheth @KevFlo Are you going to include the tutoring page also for this release?

**Comment by vyas0189** [comment]
> > @KevFlo You're missing some officers (DO CodeRED, DO Operations atleast)
> 
> I was wondering why they weren't on the website before I started working on it, will add right now

@shubhsheth @KevFlo Should we make a section for Code Red officers and CougarCS officers separately?

**Comment by shubhsheth** [comment]
> @shubhsheth @KevFlo Are you going to include the tutoring page also for this release?

No let's keep it separate, I can deploy it after Kevin reviews it's PR

**Review by shubhsheth — APPROVED** [review]

**Pull request merged**
