### PR TITLE
Hide hackathons page - Enhancement#525

### PR DESCRIPTION
**Pull request by ndminhvn**
## What type of PR is this? (check all applicable)
- [ ] ✨ Feature
- [ ] 👷 Optimization

## Description

This PR hides the Hackathons Page.

### CODE REVIEW

**Comment by LeftAutomated** [comment]
@ndminhvn For future reference, try to focus on one issue at a time so there aren't duplicate commits among the PRs. Or create a branch that doesn't branch off of a previous PR. Good work on this!
image

**Comment by ndminhvn** [comment]
> @ndminhvn For future reference, try to focus on one issue at a time so there aren't duplicate commits among the PRs. Or create a branch that doesn't branch off of a previous PR. Good work on this! image

Sorry, that was my bad. After I pushed, I realized that problem. Thank you!

**Comment by ndminhvn** [comment]
@LeftAutomated Hi, sorry for mentioning you several times. I just reverted my commits and made only one commit for this issue. Thank you!

**Review by LeftAutomated — COMMENTED** [review]
Looks good

**Pull request closed without merging**
