### PR TITLE
reworked image sizes

### PR DESCRIPTION
**Pull request by KevFlo**
reworked img size

### CODE REVIEW

**Comment by vyas0189** [comment]
Still the same issue with the images

**Comment by KevFlo** [comment]
i am noticing that the images get blurry as the cursor hovers I'm going to check I didn't crop the resized and used the original

**Comment by KevFlo** [comment]
Alright @vyas0189 @shubhsheth I believe this time I got it right. please confirm on your end

**Review by vyas0189 — APPROVED** [review]
Looks good for me

**Pull request merged**
